# Generated by Django 3.2.8 on 2021-10-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Birth_date',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Birth_place',
            new_name='birth_place',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Citizen',
            new_name='citizen',
        ),
    ]
