# Generated by Django 3.2.8 on 2021-10-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20211020_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='card_nunber',
            new_name='card_number',
        ),
    ]
