# Generated by Django 3.2.8 on 2021-10-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_rename_card_nunber_person_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personal_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
